export const breedsData = [
  // 🐶 PERROS
  { species: "perro", name: "Labrador Retriever" },
  { species: "perro", name: "Pastor Alemán" },
  { species: "perro", name: "Golden Retriever" },
  { species: "perro", name: "Bulldog" },
  { species: "perro", name: "Beagle" },
  { species: "perro", name: "Caniche (Poodle)" },
  { species: "perro", name: "Rottweiler" },
  { species: "perro", name: "Yorkshire Terrier" },
  { species: "perro", name: "Boxer" },
  { species: "perro", name: "Dachshund (Salchicha)" },
  { species: "perro", name: "Husky Siberiano" },
  { species: "perro", name: "Gran Danés" },
  { species: "perro", name: "Chihuahua" },
  { species: "perro", name: "Pomerania" },
  { species: "perro", name: "Pug" },
  { species: "perro", name: "Dálmata" },
  { species: "perro", name: "Samoyedo" },
  { species: "perro", name: "Doberman" },
  { species: "perro", name: "Alaskan Malamute" },
  { species: "perro", name: "Mestizo" },

  // 🐱 GATOS
  { species: "gato", name: "Carey (Tricolor)" },
  { species: "gato", name: "Siamés" },
  { species: "gato", name: "Persa" },
  { species: "gato", name: "Birmano" },
  { species: "gato", name: "Maine Coon" },
  { species: "gato", name: "Esfinge" },
  { species: "gato", name: "Bengalí" },
  { species: "gato", name: "Bombay" },
  { species: "gato", name: "Angora" },
  { species: "gato", name: "Ruso Azul" },
  { species: "gato", name: "Oriental" },
  { species: "gato", name: "Ginger (Naranja)" },
  { species: "gato", name: "Atigrado (Tabby)" },
  { species: "gato", name: "Esmoquin (Tuxedo)" }
];